package Dichiarativi.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_TipoCampo extends EnumerationDescriptorBase {

  public EnumerationDescriptor_TipoCampo() {
    super(0x7c951c7686284de9L, 0xb15bc69525968b60L, 0x5951c0d36d59af4dL, "TipoCampo", "r:cd7aa375-efad-498c-b280-38b726242ed0(Dichiarativi.structure)/6436137356794376013");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_N1_0 = new EnumerationDescriptor.MemberDescriptor("N1", "N1", 0x5951c0d36d59af4eL, "r:cd7aa375-efad-498c-b280-38b726242ed0(Dichiarativi.structure)/6436137356794376014");
  private final EnumerationDescriptor.MemberDescriptor myMember_N2_0 = new EnumerationDescriptor.MemberDescriptor("N2", "N2", 0x5951c0d36d59af4fL, "r:cd7aa375-efad-498c-b280-38b726242ed0(Dichiarativi.structure)/6436137356794376015");
  private final EnumerationDescriptor.MemberDescriptor myMember_N3_0 = new EnumerationDescriptor.MemberDescriptor("N3", "N3", 0x5951c0d36d59af52L, "r:cd7aa375-efad-498c-b280-38b726242ed0(Dichiarativi.structure)/6436137356794376018");
  private final EnumerationDescriptor.MemberDescriptor myMember_N4_0 = new EnumerationDescriptor.MemberDescriptor("N4", "N4", 0x5951c0d36d59af56L, "r:cd7aa375-efad-498c-b280-38b726242ed0(Dichiarativi.structure)/6436137356794376022");
  private final EnumerationDescriptor.MemberDescriptor myMember_NP_0 = new EnumerationDescriptor.MemberDescriptor("NP", "NP", 0x5951c0d36d59af5bL, "r:cd7aa375-efad-498c-b280-38b726242ed0(Dichiarativi.structure)/6436137356794376027");
  private final EnumerationDescriptor.MemberDescriptor myMember_NU_0 = new EnumerationDescriptor.MemberDescriptor("NU", "NU", 0x5951c0d36d59af61L, "r:cd7aa375-efad-498c-b280-38b726242ed0(Dichiarativi.structure)/6436137356794376033");
  private final EnumerationDescriptor.MemberDescriptor myMember_CF_0 = new EnumerationDescriptor.MemberDescriptor("CF", "CF", 0x5951c0d36d59af68L, "r:cd7aa375-efad-498c-b280-38b726242ed0(Dichiarativi.structure)/6436137356794376040");
  private final EnumerationDescriptor.MemberDescriptor myMember_PI_0 = new EnumerationDescriptor.MemberDescriptor("PI", "PI", 0x5951c0d36d59af70L, "r:cd7aa375-efad-498c-b280-38b726242ed0(Dichiarativi.structure)/6436137356794376048");
  private final EnumerationDescriptor.MemberDescriptor myMember_DT_0 = new EnumerationDescriptor.MemberDescriptor("DT", "DT", 0x5951c0d36d59af79L, "r:cd7aa375-efad-498c-b280-38b726242ed0(Dichiarativi.structure)/6436137356794376057");
  private final EnumerationDescriptor.MemberDescriptor myMember_CB_0 = new EnumerationDescriptor.MemberDescriptor("CB", "CB", 0x5951c0d36d59af83L, "r:cd7aa375-efad-498c-b280-38b726242ed0(Dichiarativi.structure)/6436137356794376067");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x7c951c7686284de9L, 0xb15bc69525968b60L, 0x5951c0d36d59af4dL, 0x5951c0d36d59af4eL, 0x5951c0d36d59af4fL, 0x5951c0d36d59af52L, 0x5951c0d36d59af56L, 0x5951c0d36d59af5bL, 0x5951c0d36d59af61L, 0x5951c0d36d59af68L, 0x5951c0d36d59af70L, 0x5951c0d36d59af79L, 0x5951c0d36d59af83L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_N1_0, myMember_N2_0, myMember_N3_0, myMember_N4_0, myMember_NP_0, myMember_NU_0, myMember_CF_0, myMember_PI_0, myMember_DT_0, myMember_CB_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "N1":
        return myMember_N1_0;
      case "N2":
        return myMember_N2_0;
      case "N3":
        return myMember_N3_0;
      case "N4":
        return myMember_N4_0;
      case "NP":
        return myMember_NP_0;
      case "NU":
        return myMember_NU_0;
      case "CF":
        return myMember_CF_0;
      case "PI":
        return myMember_PI_0;
      case "DT":
        return myMember_DT_0;
      case "CB":
        return myMember_CB_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
