package Dichiarativi.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_OrigineValore extends EnumerationDescriptorBase {

  public EnumerationDescriptor_OrigineValore() {
    super(0x7c951c7686284de9L, 0xb15bc69525968b60L, 0x5951c0d36d59b3b5L, "OrigineValore", "r:cd7aa375-efad-498c-b280-38b726242ed0(Dichiarativi.structure)/6436137356794377141");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Calcolato_0 = new EnumerationDescriptor.MemberDescriptor("Calcolato", "Calcolato", 0x5951c0d36d59b3b6L, "r:cd7aa375-efad-498c-b280-38b726242ed0(Dichiarativi.structure)/6436137356794377142");
  private final EnumerationDescriptor.MemberDescriptor myMember_Contabilita_0 = new EnumerationDescriptor.MemberDescriptor("Contabilita", "Contabilita", 0x5951c0d36d59b3b7L, "r:cd7aa375-efad-498c-b280-38b726242ed0(Dichiarativi.structure)/6436137356794377143");
  private final EnumerationDescriptor.MemberDescriptor myMember_Manuale_0 = new EnumerationDescriptor.MemberDescriptor("Manuale", "Manuale", 0x5951c0d36d59b3baL, "r:cd7aa375-efad-498c-b280-38b726242ed0(Dichiarativi.structure)/6436137356794377146");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x7c951c7686284de9L, 0xb15bc69525968b60L, 0x5951c0d36d59b3b5L, 0x5951c0d36d59b3b6L, 0x5951c0d36d59b3b7L, 0x5951c0d36d59b3baL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Calcolato_0, myMember_Contabilita_0, myMember_Manuale_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Calcolato":
        return myMember_Calcolato_0;
      case "Contabilita":
        return myMember_Contabilita_0;
      case "Manuale":
        return myMember_Manuale_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
