package Dichiarativi.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCampo = createDescriptorForCampo();
  /*package*/ final ConceptDescriptor myConceptDichiarazione = createDescriptorForDichiarazione();
  /*package*/ final ConceptDescriptor myConceptQuadro = createDescriptorForQuadro();
  /*package*/ final EnumerationDescriptor myEnumerationOrigineValore = new EnumerationDescriptor_OrigineValore();
  /*package*/ final EnumerationDescriptor myEnumerationTipoCampo = new EnumerationDescriptor_TipoCampo();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCampo, myConceptDichiarazione, myConceptQuadro);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Campo:
        return myConceptCampo;
      case LanguageConceptSwitch.Dichiarazione:
        return myConceptDichiarazione;
      case LanguageConceptSwitch.Quadro:
        return myConceptQuadro;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationOrigineValore, myEnumerationTipoCampo);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCampo() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Dichiarativi", "Campo", 0x7c951c7686284de9L, 0xb15bc69525968b60L, 0x5951c0d36d59af47L);
    b.class_(false, false, false);
    b.origin("r:cd7aa375-efad-498c-b280-38b726242ed0(Dichiarativi.structure)/6436137356794376007");
    b.version(3);
    b.property("codice", 0x5951c0d36d59af48L).type(PrimitiveTypeId.STRING).origin("6436137356794376008").done();
    b.property("tipo", 0x5951c0d36d59af4aL).type(MetaIdFactory.dataTypeId(0x7c951c7686284de9L, 0xb15bc69525968b60L, 0x5951c0d36d59af4dL)).origin("6436137356794376010").done();
    b.property("Origine", 0x5951c0d36d59b3c2L).type(MetaIdFactory.dataTypeId(0x7c951c7686284de9L, 0xb15bc69525968b60L, 0x5951c0d36d59b3b5L)).origin("6436137356794377154").done();
    b.alias("campo");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDichiarazione() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Dichiarativi", "Dichiarazione", 0x7c951c7686284de9L, 0xb15bc69525968b60L, 0x5951c0d36d59a811L);
    b.class_(false, false, true);
    b.origin("r:cd7aa375-efad-498c-b280-38b726242ed0(Dichiarativi.structure)/6436137356794374161");
    b.version(3);
    b.property("Nome", 0x5951c0d36d59a825L).type(PrimitiveTypeId.STRING).origin("6436137356794374181").done();
    b.aggregate("quadri", 0x5951c0d36d59a829L).target(0x7c951c7686284de9L, 0xb15bc69525968b60L, 0x5951c0d36d59a7daL).optional(false).ordered(true).multiple(true).origin("6436137356794374185").done();
    b.alias("Dichiarazione");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForQuadro() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Dichiarativi", "Quadro", 0x7c951c7686284de9L, 0xb15bc69525968b60L, 0x5951c0d36d59a7daL);
    b.class_(false, false, false);
    b.origin("r:cd7aa375-efad-498c-b280-38b726242ed0(Dichiarativi.structure)/6436137356794374106");
    b.version(3);
    b.property("Nome", 0x5951c0d36d59a80fL).type(PrimitiveTypeId.STRING).origin("6436137356794374159").done();
    b.property("MultiModulo", 0x5951c0d36d59b3c6L).type(PrimitiveTypeId.BOOLEAN).origin("6436137356794377158").done();
    b.aggregate("Campi", 0x5951c0d36d59af91L).target(0x7c951c7686284de9L, 0xb15bc69525968b60L, 0x5951c0d36d59af47L).optional(false).ordered(true).multiple(true).origin("6436137356794376081").done();
    b.alias("Quadro");
    return b.create();
  }
}
